### ISSUE TITLE
Compiling throws an error due to extra paranthesis

### ISSUE THREAD

**Issue by brandon-zhang** [xinabox/xSN01#3]
Arduino error log:

C:\Users\bzhang\Documents\Arduino\libraries\xSN01-master\src\xSN01.cpp:132:25: error: expected ';' before ')' token

  return (mySN01.NumSats));

**Comment by brendanvanbreda** [comment]
@brandon-zhang should be fixed now.

Please state if it can be closed now ?

**Comment by brandon-zhang** [comment]
Yup, looks good to me! Thanks
